apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../controller
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: randomstringset-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/mightyshazam/random-name-controller:v0.1.0
