apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: randomstringset-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: randomstrings.io/v1
    resource: randomstringsets
  childResources:
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: OnDelete
  hooks:
    sync:
      webhook:
        url: http://randomstringset-controller.default/sync
        timeout: 1m
